version: "2"
services:
  broadcast:
    build: .
    command: /opt/anyjob/bin/anyjobd.pl
    links:
     - redis
    environment:
     - ANYJOB_NODE=broadcast
  example:
    build: .
    command: /opt/anyjob/bin/anyjobd.pl
    links:
     - redis
    environment:
     - ANYJOB_NODE=example
  creator:
    build: .
    command: /usr/local/bin/plackup --server Twiggy --port 80 --no-default-middleware /opt/anyjob/bin/anyjobc.psgi
    links:
     - redis
    ports:
     - "0.0.0.0:80:80"
  redis:
    image: redis
    ports:
     - "0.0.0.0:6379:6379"
