version: "2"
services:
  broadcast:
    build: .
    command: /opt/anyjob/bin/anyjobd.pl
    links:
     - redis
    environment:
     - ANYJOB_NODE=broadcast
  test:
    build: .
    command: /opt/anyjob/bin/anyjobd.pl
    links:
     - redis
    environment:
     - ANYJOB_NODE=test
  creator:
    build: .
    command: /usr/local/bin/plackup -s Twiggy -p 80 /opt/anyjob/bin/anyjobc.pl
    links:
     - redis
    ports:
     - "0.0.0.0:80:80"
  redis:
    image: redis
    ports:
     - "0.0.0.0:6379:6379"
